# Generated by Django 5.1.6 on 2025-06-25 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomDes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DomDes_nom', models.CharField(max_length=100)),
                ('DomDes_obj', models.CharField(max_length=100)),
                ('DomDes_ben', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DomEco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DomEco_nom', models.CharField(max_length=100)),
                ('DomEco_desc', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MarcoMetodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marco_tipo', models.CharField(max_length=100)),
                ('Marco_nom', models.CharField(max_length=200)),
                ('Marco_desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomDesComent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DomDesComent_orden', models.IntegerField(default=0)),
                ('DomDesComent_tit', models.CharField(max_length=100)),
                ('DomDesComent_desc', models.TextField(blank=True)),
                ('DomDes_Url', models.URLField(blank=True, null=True)),
                ('DomDes_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.domdes')),
            ],
        ),
        migrations.AddField(
            model_name='domdes',
            name='DomEco_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.domeco'),
        ),
        migrations.CreateModel(
            name='MarcoObs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marc_Obs_orden', models.IntegerField(default=0)),
                ('Marc_Obs_nom', models.CharField(max_length=200)),
                ('Marc_Obs_desc', models.TextField(blank=True)),
                ('Marco_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.marcometodo')),
            ],
        ),
        migrations.CreateModel(
            name='MMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MMA_tipo', models.CharField(max_length=50)),
                ('MMA_clase', models.CharField(max_length=200)),
                ('MMA_nom', models.CharField(max_length=200)),
                ('MMA_desc', models.TextField(blank=True)),
                ('DominiosDes', models.ManyToManyField(to='datos.domdes')),
                ('Marcos', models.ManyToManyField(to='datos.marcometodo')),
            ],
        ),
        migrations.CreateModel(
            name='MMAElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MMAElem_orden', models.IntegerField(default=0)),
                ('MMAElem_nom', models.CharField(max_length=200)),
                ('MMAElem_desc', models.TextField(blank=True)),
                ('MMAElem_Url', models.URLField(blank=True, null=True)),
                ('MMA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.mma')),
            ],
        ),
        migrations.CreateModel(
            name='PPV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PPV_tipo', models.CharField(max_length=100)),
                ('PPV_nom', models.CharField(max_length=100)),
                ('PPV_obj', models.TextField()),
                ('PPV_desc', models.TextField(blank=True)),
                ('Marco_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.marcometodo')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rol_nom', models.CharField(max_length=100)),
                ('Rol_desc', models.TextField(blank=True)),
                ('Marco_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.marcometodo')),
            ],
        ),
        migrations.CreateModel(
            name='EcoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EcoTarea_orden', models.IntegerField(default=0)),
                ('EcoTarea_nom', models.CharField(max_length=100)),
                ('EcoTarea_desc', models.CharField(max_length=100)),
                ('EcoTarea_obs', models.TextField(blank=True)),
                ('DomEco_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.domeco')),
                ('TRoles', models.ManyToManyField(to='datos.rol')),
            ],
        ),
        migrations.CreateModel(
            name='EcoFacilitador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EcoFacilitador_orden', models.IntegerField(default=0)),
                ('EcoFacilitador_nom', models.CharField(max_length=100)),
                ('EcoFacilitador_obs', models.TextField()),
                ('EcoTarea_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.ecotarea')),
                ('FRoles', models.ManyToManyField(to='datos.rol')),
            ],
        ),
    ]
